name: build and push
on:
  push: {}
  repository_dispatch:
    types: [run]
jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [18, 20, 22]
    env:
      STACK_VERSION: ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
# CNB are not multi-arch ready as of May 2022 so this is not needed
# It causes problems with this workflow so test later
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push for stack ${{ env.STACK_VERSION }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            STACK_VERSION=-${{ env.STACK_VERSION }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}:latest-${{ env.STACK_VERSION }}
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
# acdhch/${{ inputs.image_tagged }}
