name: build and push
on:
  push: {}
  repository_dispatch:
    types: [run]
jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
# CNB are not multi-arch ready as of May 2022 so this is not needed
# It causes problems with this workflow so test later
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}:latest-18
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}
      - name: Build and push for stack 20.04
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            STACK_VERSION=-20
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ github.ref_name }}:latest-20
# acdhch/${{ inputs.image_tagged }}
